# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 081943ecfa932e9db0490eb237ce32a91849ed474611385df3e9ce071aab19f3e90f94642d317101c262d804de8e1ca31e146c223a43f47e74d21a506d949af3

test:
  secret_key_base: e8c092588944149b4fb555d7922b92d8e6922208114b821305d330c22872481e875873f9c26798b080b97254d7741b0d8b8c6b1244f2aa3734ad0224066420e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
